name: ctmanager
description: A Cloudflared Manager application.
version: 0.6.0
publish_to: 'none'

environment:
  sdk: ">=2.18.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  provider: ^6.1.1
  sqflite: ^2.3.0
  sqflite_common_ffi: ^2.3.2+1
  sqlite3: ^2.3.0
  path: ^1.8.3
  path_provider: ^2.1.1
  http: ^0.13.6
  shared_preferences: 2.0.18
  logger: ^1.4.0
  process: ^4.2.4
  url_launcher: ^6.2.4
  msix: ^3.16.8
  file_picker: ^6.1.1
  win32: ^5.2.0
  ffi: ^2.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  flutter_launcher_icons: ^0.13.1

flutter:
  uses-material-design: true
  assets:
    - assets/

# Icon configuration for all platforms
flutter_icons:
  android: true
  ios: true
  windows:
    generate: true
    icon_size: 256
  macos:
    generate: true
  linux:
    generate: true
  web:
    generate: true
  image_path: "assets/icon.jpg"
  adaptive_icon_background: "#FFFFFF"
  adaptive_icon_foreground: "assets/icon.jpg"
  remove_alpha_ios: true
  min_sdk_android: 21

msix_config:
  display_name: Cloudflare Tunnel Manager
  publisher_display_name: CTManager
  identity_name: com.ctmanager.app
  msix_version: 0.6.0.0
  logo_path: assets/icon.jpg
  capabilities: internetClient
  certificate_path: CERTIFICATE.pfx
  certificate_password: 1234567890
  install_certificate: true
  store: false  # Set to true if publishing to Microsoft Store
  dependencies:
    Microsoft.VCLibs.140.00:
      path: assets/dependencies/Microsoft.VCLibs.x64.14.00.Desktop.appx
    Microsoft.VCLibs.140.00.UWPDesktop:
      path: assets/dependencies/Microsoft.VCLibs.x64.14.00.Desktop.appx
  execution_alias: ctmanager
  add_execution_alias: true
